<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robovisor">

	<joint name="chassis_joint" type="fixed">
		<parent link="base_link"/>
		<child link="chassis_link"/>
		<origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
	</joint>

	<joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

	<joint name="left_wheel_joint" type="continuous">
		<parent link="chassis_link"/>
		<child link="left_wheel"/>
		<origin xyz="-${chassis_length/4} ${chassis_width/2} 0" rpy="-${pi/2} 0 0"/>
		<axis xyz="0 0 1"/>
	</joint>

	<joint name="right_wheel_joint" type="continuous">
		<parent link="chassis_link"/>
		<child link="right_wheel"/>
		<origin xyz="-${chassis_length/4} -${chassis_width/2} 0" rpy="${pi/2} 0 0"/>
		<axis xyz="0 0 -1"/>
	</joint>

	<joint name="front_wheel_joint" type="fixed">
		<parent link="chassis_link"/>
		<child link="front_wheel"/>
		<origin xyz="${chassis_length/4} 0 -${chassis_height/2}" rpy="0 0 0"/>
	</joint>

	<joint name="lidar_support_joint" type="fixed">
		<parent link="chassis_link"/>
		<child link="lidar_support"/>
		<origin xyz="-${chassis_length/4} 0 ${chassis_height/2 + lidar_length/2}" rpy="0 0 0"/>
	</joint>

	<joint name="lidar_joint" type="fixed">
		<parent link="lidar_support"/>
		<child link="lidar_link"/>
		<origin xyz="0 0 ${lidar_length}" rpy="0 0 0"/>
	</joint>
</robot>