<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robovisor">

	<joint name="left_wheel_joint" type="continuous">
		<parent link="base_link"/>
		<child link="left_wheel"/>
		<origin xyz="-${chassis_length/4} ${chassis_width/2} ${wheel_radius}" rpy="-${pi/2} 0 0"/>
		<axis xyz="0 0 1"/>
	</joint>

	<joint name="right_wheel_joint" type="continuous">
		<parent link="base_link"/>
		<child link="right_wheel"/>
		<origin xyz="-${chassis_length/4} -${chassis_width/2} ${wheel_radius}" rpy="${pi/2} 0 0"/>
		<axis xyz="0 0 -1"/>
	</joint>

	<joint name="front_wheel_joint" type="fixed">
		<parent link="base_link"/>
		<child link="front_wheel"/>
		<origin xyz="${chassis_length/4} 0 ${wheel_radius-chassis_height/2}" rpy="0 0 0"/>
	</joint>

	<joint name="lidar_support_joint" type="fixed">
		<parent link="base_link"/>
		<child link="lidar_support"/>
		<origin xyz="-${chassis_length/4} 0 ${wheel_radius + chassis_height/2 + lidar_length/2}" rpy="0 0 0"/>
	</joint>

	<joint name="lidar_joint" type="fixed">
		<parent link="lidar_support"/>
		<child link="lidar_link"/>
		<origin xyz="0 0 ${lidar_length}" rpy="0 0 0"/>
	</joint>
</robot>