<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robo_dc">

	<gazebo>
		<plugin name="diff_drive" filename="libgazebo_ros_diff_drive.so">
			<left_joint>left_wheel_joint</left_joint>
			<right_joint>right_wheel_joint</right_joint>

			<wheel_separation>${chassis_radius*2 - wheel_length}</wheel_separation>
			<wheel_diameter>${2*wheel_radius}</wheel_diameter>

			<max_wheel_torque>200</max_wheel_torque>
			<max_wheel_acceleration>10.0</max_wheel_acceleration>

			<odometry_frame>odom</odometry_frame>
			<robot_base_frame>base_link</robot_base_frame>
			
			<publish_odom>true</publish_odom>
			<publish_odom_tf>true</publish_odom_tf>
			<publish_wheel_tf>true</publish_wheel_tf>
		</plugin>
	</gazebo>

	<gazebo reference="laser_link">
		<sensor name="lidar" type="ray">
			<pose> 0 0 0 0 0 0 </pose>
			<visualize>true</visualize>
			<update_rate>10</update_rate>

			<ray>
				<scan>
					<horizontal>
						<samples>360</samples>
						<min_angle>-${pi/2 + pi/20}</min_angle>
						<max_angle>${pi/2 + pi/20}</max_angle>
					</horizontal>
				</scan>
				<range>
					<min>0.3</min>
					<max>20</max>
				</range>
			</ray>
			<plugin name="lidar_controller" filename="libgazebo_ros_ray_sensor.so">
				<ros>
					<argument>~/out:=scan</argument>
				</ros>
				<output_type>sensor_msgs/LaserScan</output_type>
				<frame_name>laser_link</frame_name>
			</plugin>
		</sensor>
	</gazebo>

	<gazebo reference="caster_n_link">
		<mu1>0.2</mu1>
		<mu2>0.2</mu2>
	</gazebo>

	<gazebo reference="caster_s_link">
		<mu1>0.2</mu1>
		<mu2>0.2</mu2>
	</gazebo>

</robot>