<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robovisor">

	<link name="pillar_ne_link">
		<visual>
			<geometry>
				<box size="${pillar_length} ${pillar_width} ${pillar_height}"/>
			</geometry>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<material name="pillar_color">
				<color rgba="${white}"/>
			</material>
		</visual>

		<collision>
			<geometry>
				<box size="${pillar_length} ${pillar_width} ${pillar_height}"/>
			</geometry>
			<origin xyz="0 0 0" rpy="0 0 0"/>
		</collision>

		<xacro:inertial_box mass="1"  x="${pillar_length}" y="${pillar_width}" z="${pillar_height}">
			<origin xyz="0 0 0" rpy="0 0 0"/>
		</xacro:inertial_box>
	</link>

	<link name="pillar_nw_link">
		<visual>
			<geometry>
				<box size="${pillar_length} ${pillar_width} ${pillar_height}"/>
			</geometry>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<material name="pillar_color">
				<color rgba="${white}"/>
			</material>
		</visual>

		<collision>
			<geometry>
				<box size="${pillar_length} ${pillar_width} ${pillar_height}"/>
			</geometry>
			<origin xyz="0 0 0" rpy="0 0 0"/>
		</collision>

		<xacro:inertial_box mass="1" x="${pillar_length}" y="${pillar_width}" z="${pillar_height}">
			<origin xyz="0 0 0" rpy="0 0 0"/>
		</xacro:inertial_box>
	</link>
	
	<link name="pillar_se_link">
		<visual>
			<geometry>
				<box size="${pillar_length} ${pillar_width} ${pillar_height}"/>
			</geometry>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<material name="pillar_color">
				<color rgba="${white}"/>
			</material>
		</visual>

		<collision>
			<geometry>
				<box size="${pillar_length} ${pillar_width} ${pillar_height}"/>
			</geometry>
			<origin xyz="0 0 0" rpy="0 0 0"/>
		</collision>

		<xacro:inertial_box mass="1"  x="${pillar_length}" y="${pillar_width}" z="${pillar_height}">
			<origin xyz="0 0 0" rpy="0 0 0"/>
		</xacro:inertial_box>
	</link>

	<link name="pillar_sw_link">
		<visual>
			<geometry>
				<box size="${pillar_length} ${pillar_width} ${pillar_height}"/>
			</geometry>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<material name="pillar_color">
				<color rgba="${white}"/>
			</material>
		</visual>

		<collision>
			<geometry>
				<box size="${pillar_length} ${pillar_width} ${pillar_height}"/>
			</geometry>
			<origin xyz="0 0 0" rpy="0 0 0"/>
		</collision>

		<xacro:inertial_box mass="1"  x="${pillar_length}" y="${pillar_width}" z="${pillar_height}">
			<origin xyz="0 0 0" rpy="0 0 0"/>
		</xacro:inertial_box>
	</link>

	<joint name="pillar_ne_joint" type="fixed">
		<parent link="chassis_link"/>
		<child link="pillar_ne_link"/>
		<origin xyz="${3*chassis_radius/5} ${3*chassis_radius/5} ${pillar_height/2}" rpy="0 0 ${pi/4}"/>
	</joint>

	<joint name="pillar_nw_joint" type="fixed">
		<parent link="chassis_link"/>
		<child link="pillar_nw_link"/>
		<origin xyz="${3*chassis_radius/5} -${3*chassis_radius/5} ${pillar_height/2}" rpy="0 0 -${pi/4}"/>
	</joint>

	<joint name="pillar_se_joint" type="fixed">
		<parent link="chassis_link"/>
		<child link="pillar_se_link"/>
		<origin xyz="-${3*chassis_radius/5} ${3*chassis_radius/5} ${pillar_height/2}" rpy="0 0 -${pi/4}"/>
	</joint>

	<joint name="pillar_sw_joint" type="fixed">
		<parent link="chassis_link"/>
		<child link="pillar_sw_link"/>
		<origin xyz="-${3*chassis_radius/5} -${3*chassis_radius/5} ${pillar_height/2}" rpy="0 0 ${pi/4}"/>
	</joint>

</robot>