<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robovisor">

	<link name="chassis_link">
		<visual>
			<geometry>
				<cylinder radius="${chassis_radius}" length="${chassis_length}"/>
			</geometry>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<material name="body_color">
				<color rgba="${white}"/>
			</material>
		</visual>

		<collision>
			<geometry>
				<cylinder radius="${chassis_radius}" length="${chassis_length}"/>
			</geometry>
			<origin xyz="0 0 0" rpy="0 0 0"/>
		</collision>

		<xacro:inertial_cylinder mass="1" radius="${chassis_radius}" length="${chassis_length}">
			<origin xyz="0 0 0" rpy="0 0 0"/>
		</xacro:inertial_cylinder>
	</link>

	<joint name="chassis_joint" type="fixed">
		<parent link="base_link"/>
		<child link="chassis_link"/>
		<origin xyz="0 0 ${wheel_radius - driver_radius*2}" rpy="0 0 0"/>
	</joint>

</robot>