<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robovisor">

	<link name="laser_link">
		<visual>
			<geometry>
				<cylinder radius="${laser_radius}" length="${laser_length}"/>
			</geometry>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<material name="laser_color">
				<color rgba="${purple}"/>
			</material>
		</visual>

		<collision>
			<geometry>
				<cylinder radius="${laser_radius}" length="${laser_length}"/>
			</geometry>
			<origin xyz="0 0 0" rpy="0 0 0"/>
		</collision>

		<xacro:inertial_cylinder mass="1" radius="${laser_radius}" length="${laser_length}">
			<origin xyz="0 0 0" rpy="0 0 0"/>
		</xacro:inertial_cylinder>
	</link>

	<joint name="laser_joint" type="fixed">
		<parent link="chassis_link"/>
		<child link="laser_link"/>
		<origin xyz="${chassis_radius - laser_radius} 0 ${laser_length/2}" rpy="0 0 0"/>
	</joint>

</robot>